### PR TITLE
Add Projectile support

### PR DESCRIPTION
**Pull request by d125q**
Implements `buffer-expose-project{,-{,no-}stars}`.

### CODE REVIEW

**Comment by clemera** [comment]
Thank you!

Did you sign the FSF copyright assignment? If not, do you want to [sign](https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future) it? `buffer-expose` in on GNU ELPA and this is required.

**Comment by d125q** [comment]
I will sign it and report back.  Thank you likewise!

**Comment by clemera** [comment]
Great! This will allow you to contribute to Emacs and other GNU ELPA projects in the future, too.

**Comment by d125q** [comment]
I have signed the copyright assignment and sent it back.  Not sure if waiting for the FSF to send me a copy back is necessary.

**Comment by clemera** [comment]
Great! I'm not sure, so lets wait a bit, usually it does not take more than a few days.

**Comment by d125q** [comment]
I have received my copy of the copyright assignment.

**Comment by clemera** [comment]
Thank you again! Now it's merged!

**Pull request merged**
