### PR TITLE
Make it work in non-graphical environment

### PR DESCRIPTION
**Pull request by 10sr**
When Emacs was compiled without graphcal support, `fringe-mode` and `scroll-bar-mode` are not defined. So just ignore them when they do not exist.

### CODE REVIEW

**Comment by clemera** [comment]
Thank you! 

Did you sign the FSF copyright assignment? If not, do you want to [sing](https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future) it? `buffer-expose` in on GNU ELPA and this is required. If you don't want to sign, I will add the changes myself.

**Comment by 10sr** [comment]
OK, I'll do it! 🙌

**Comment by clemera** [comment]
Great, please ping back here, when it's done.

**Comment by 10sr** [comment]
Hi, @clemera, 
I've completed the copyright assignment process and got the PDF with both signs, so I think this patch can be merged now!
(Please let me know if I have something more to do for this. I'm not very familiar with this process)

**Comment by clemera** [comment]
Thank you so much!

**Comment by clemera** [comment]
BTW now that you have signed the papers you are able to contribute to Emacs itself and other GNU ELPA packages in the future.

**Comment by 10sr** [comment]
Thanks! 🎉 🎉  🎉

**Pull request closed without merging**
